version: '3'
services:

  client:
    entrypoint:
      npm run start
    build:
      context: client
      dockerfile: Dockerfile
    ports:
    - 3000:3000
    depends_on:
    - server
  server:
    restart: always
    entrypoint:
        node build/index
    build:
      context: server
      dockerfile: Dockerfile
    ports:
    - 8080:8080
    depends_on:
    - mongodb
    environment:
      - mongoDomain=mongodb
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - 27017:27017