version: '3'
services:

  server:
    restart: always
    entrypoint:
        node build/index
    build:
      context: server
      dockerfile: Dockerfile
    ports:
    - 8080:8080
    depends_on:
    - nextMongodb
    environment:
      - mongoDomain=nextMongodb
  nextMongodb:
    image: mongo
    restart: always
    container_name: nextMongodb
    ports:
      - 27017:27017